---
title: "Processing Conway"
format: html
---

# Set up

## packages
```{r}
#| warning: false
#| label: load packages
library(tidyverse)
library(cowplot)
library(kableExtra)
theme_set(theme_cowplot())
```

# load conway
```{r}
#| label: loading conway
conwayIndividRaw <- read.csv("/Users/katherinehayes/Google Drive/Projects/NSF Postdoc/Manuscripts/ConwayAgeGrowth/data/Conway_Exclosure.csv")

colnames(conwayIndividRaw)

summary(conwayIndividRaw)

kable(head(conwayIndividRaw))
```

## height
```{r Conway cleaning}
#| warning: false
conwayHeight <- conwayIndividRaw %>%
  select(Site, Treatment, Species, IndTag, Height2013, Height2014,
         Height2015, Height2017) %>%
  mutate(Height2014 = as.numeric(Height2014), # omit NAs
         Height2015 = as.numeric(Height2015),
         Height2017 = as.numeric(Height2017)) %>%
  pivot_longer(cols = c(Height2013, Height2015, 
                        Height2014, Height2017),
               names_to = "Year", values_to = "Height") %>%
  mutate(year = ifelse(Year == "Height2014", 2014,
                       ifelse(Year == "Height2015", 2015,
                              ifelse(Year == "Height2013", 2013,
                                     ifelse(Year == "Height2017",
                                            2017, NA))))) %>%
  mutate(TSF = year - 2005) %>% # calculate TSF
  mutate(height = Height / 100) %>% # transform height from 
  mutate(Scenario = ifelse(Treatment == "Control", 
                            "Browsing", "No Browsing")) %>%
  ungroup() %>%
  drop_na(height) %>%
  select(!c(IndTag, Year))

summary(conwayHeight)

kable(head(conwayHeight))

# rename species to match
conwayHeight <- conwayHeight %>%
  mutate(species = ifelse(Species == "aspen", "Potr",
                       ifelse(Species == "birch", "Bene",
                              "Pima")))
```

## DBH
```{r Conway cleaning}
#| warning: false
conwayDBH <- conwayIndividRaw %>%
  select(Site, Treatment, Species, IndTag, DBH2013, DBH2014,
         DBH2015, DBH2017) %>%
  mutate(DBH2014 = as.numeric(DBH2014), # omit NAs
         DBH2013 = as.numeric(DBH2013),
         DBH2015 = as.numeric(DBH2015),
         DBH2017 = as.numeric(DBH2017)) %>%
  pivot_longer(cols = c(DBH2013, DBH2015, 
                        DBH2014, DBH2017),
               names_to = "Year", values_to = "DBH") %>%
  mutate(year = ifelse(Year == "DBH2014", 2014,
                       ifelse(Year == "DBH2015", 2015,
                              ifelse(Year == "DBH2013", 2013,
                                     ifelse(Year == "DBH2017",
                                            2017, NA))))) %>%
  mutate(TSF = year - 2005) %>% # calculate TSF
  mutate(Scenario = ifelse(Treatment == "Control", 
                            "Browsing", "No Browsing")) %>%
  ungroup() %>%
  drop_na(DBH) %>%
  select(!c(IndTag, Year))

summary(conwayDBH)

kable(head(conwayDBH))

# rename species to match
conwayDBH <- conwayDBH %>%
  mutate(species = ifelse(Species == "aspen", "Potr",
                       ifelse(Species == "birch", "Bene",
                              "Pima")))
```


## Basal
```{r Conway cleaning}
#| warning: false
conwayBasal <- conwayIndividRaw %>%
  select(Site, Treatment, Species, IndTag, Basal2013, Basal2014,
         Basal2015, Basal2017) %>%
  mutate(Basal2014 = as.numeric(Basal2014), # omit NAs
         Basal2013 = as.numeric(Basal2013),
         Basal2015 = as.numeric(Basal2015),
         Basal2017 = as.numeric(Basal2017)) %>%
  pivot_longer(cols = c(Basal2013, Basal2015, 
                        Basal2014, Basal2017),
               names_to = "Year", values_to = "basal") %>%
  mutate(year = ifelse(Year == "Basal2014", 2014,
                       ifelse(Year == "Basal2015", 2015,
                              ifelse(Year == "Basal2013", 2013,
                                     ifelse(Year == "Basal2017",
                                            2017, NA))))) %>%
  mutate(TSF = year - 2005) %>% # calculate TSF
  mutate(Scenario = ifelse(Treatment == "Control", 
                            "Browsing", "No Browsing")) %>%
  ungroup() %>%
  drop_na(basal) %>%
  select(!c(IndTag, Year))

summary(conwayBasal)

kable(head(conwayBasal))

# rename species to match
conwayBasal <- conwayBasal %>%
  mutate(species = ifelse(Species == "aspen", "Potr",
                       ifelse(Species == "birch", "Bene",
                              "Pima")))
```

# Site averages

```{r conway site avs}
conwayHeightSite <- conwayHeight %>%
  group_by(Scenario, TSF, Site, species) %>%
  summarise(mean = mean(height),
            sd = sd(height, na.rm = TRUE)) %>%
  mutate(mean = round(mean, 2),
         low = sd - mean,
         high = sd + mean) %>%
  mutate(Data = "Field",
         variable = "height")

conwayDBHSite <- conwayDBH %>%
  group_by(Scenario, TSF, Site, species) %>%
  summarise(mean = mean(DBH),
            sd = sd(DBH, na.rm = TRUE)) %>%
  mutate(mean = round(mean, 2),
         low = sd - mean,
         high = sd + mean) %>%
  mutate(Data = "Field",
         variable = "DBH")

conwayBasalSite <- conwayBasal %>%
  group_by(Scenario, TSF, Site, species) %>%
  summarise(mean = mean(basal),
            sd = sd(basal, na.rm = TRUE)) %>%
  mutate(mean = round(mean, 2),
         low = sd - mean,
         high = sd + mean) %>%
  mutate(Data = "Field",
         variable = "basal")

conwaySite <- full_join(conwayHeightSite, conwayDBHSite)
conwaySite <- full_join(conwaySite, conwayBasalSite)


summary(conwaySite)

write.csv(conwaySite, "/Users/katherinehayes/Google Drive/Projects/NSF Postdoc/Manuscripts/ConwayAgeGrowth/data/Conway_data.csv", row.names = FALSE)
```